cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/',
         views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',
         views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('list/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 51)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Quantity'))
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    coupon_apply_form = CouponApplyForm
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% load i18n %}

{% load static %}

{% block title %}{% trans "Cart" %}{% endblock %}

{% block content %}

<table class="table table-dark table-hover" id='cart'>
    <thead>
        <tr>
            <th scope="col">{% trans "Image" %}</th>
            <th scope="col">{% trans "Product" %}</th>
            <th scope="col">{% trans "Quantity" %}</th>
            <th scope="col">{% trans "Remove" %}</th>
            <th scope="col">{% trans "Unit Price" %}</th>
            <th scope="col">{% trans "Price" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <div class="tabcard">
                    <a href="{{ product.get_absolute_url }}">
                        <img
                            src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'image/noimage.png' %} {% endif %}">
                    </a>
                </div>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input type="submit" class="btn btn-warning" value="{% trans 'Update' %}">
                    {% csrf_token %}
                </form>
            </td>
            <td>
                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                    <input type="submit" class="btn btn-danger" value="{% trans 'Remove' %}">
                    {% csrf_token %}
                </form>
            </td>
            <td class="num">{%trans "Rs" %}.{{ item.price }}</td>
            <td class="num">{%trans "Rs" %}.{{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
        <tr class="subtotal">
            <td>{% trans "Subtotal" %}</td>
            <td colspan="4"></td>
            <td class="num">{%trans "Rs" %}.{{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
            <td>
                "{{ cart.coupon.code }}" {% trans "Coupon" %}
                ({{ cart.coupon.discount }}% {% trans "off" %})
            </td>
            <td colspan="4"></td>
            <td class="num neg"> - {%trans "Rs" %}.{{ cart.get_discount|floatformat:2 }}</td>
        </tr>
        {% endif %}
        <tr class="total">
            <td>{% trans 'total' %}</td>
            <td colspan="4"></td>
            <td class="num">{% trans "Rs" %}.{{ cart.get_total_price_after_discount|floatformat:2 }}</td>
        </tr>
    </tbody>
</table>

<span class="card text-center" style="width: 18rem; margin-left: 540px;">
    <div class="card-body">
        <h5 class="card-title fw-bold">{% trans "Apply Coupon" %}</h5>
        <form action="{% url 'coupons:apply' %}" method="post">
            {{ coupon_apply_form.as_p }}
            {% csrf_token %}
            <input type="submit" value="{% trans 'Apply' %}" class="btn btn-primary">
        </form>
        <br>
        <small class="card-subtitle mb-2 text-muted">{%  trans "Pick One" %}</small>
        <hr>
        <a href="{% url 'shop:product_list' %}" class="btn btn-success">{% trans "Shop More" %}</a>
        <a href="{% url 'orders:order_create' %}" class="btn btn-warning">{% trans "Checkout" %}</a>

    </div>
</span>


{% endblock %}